/* =========================================================
   🧱 Construye paso a paso — tú pones la lógica, escribes el comando.
   Cada paso: [lógica en español, pista (nivel 1), respuestas aceptadas, sangría]
   La primera respuesta es la que se muestra en el código final.
   ========================================================= */

const BUILDS = [
  {
    id: 'b-stock', unit: 'err', db: 'farmacia', title: 'Verificar stock con TRY/CATCH',
    text: 'Revisa el stock del medicamento <b>5</b>. Si es menor a 10 lanza el error <b>STOCK INSUFICIENTE</b>; si no, imprime <b>SE PUEDE VENDER</b>. Controla el error.',
    steps: [
      ['Declara la variable @stock de tipo INT', 'DECLARE @<var> <TIPO>', ['DECLARE @stock INT'], 0],
      ['Abre el bloque que “intenta”', 'BEGIN ___', ['BEGIN TRY'], 0],
      ['Guarda en @stock el Stock del medicamento 5', 'SELECT @var = <columna> FROM <tabla> WHERE <id> = 5', ['SELECT @stock = Stock FROM Medicamentos WHERE IdMed = 5'], 1],
      ['Si @stock es menor que 10…', 'IF <condición>', ['IF @stock < 10'], 1],
      ['…lanza el error STOCK INSUFICIENTE (que sí salte al CATCH)', "RAISERROR('<mensaje>', <severidad>, <estado>)", ["RAISERROR('STOCK INSUFICIENTE', 16, 1)"], 2],
      ["Si todo pasó, imprime 'SE PUEDE VENDER'", "PRINT '<texto>'", ["PRINT 'SE PUEDE VENDER'"], 1],
      ['Cierra el bloque que intenta', 'END ___', ['END TRY'], 0],
      ['Abre el bloque que “atrapa” el error', 'BEGIN ___', ['BEGIN CATCH'], 0],
      ["Imprime 'Error: ' + el texto del error", "PRINT '<texto>' + <función>()", ["PRINT 'Error: ' + ERROR_MESSAGE()"], 1],
      ['Cierra el bloque que atrapa', 'END ___', ['END CATCH'], 0],
    ],
  },
  {
    id: 'b-output', unit: 'sp', db: 'clinica', title: 'SP con parámetro OUTPUT',
    text: 'Crea <b>uspContarCitas</b> que reciba el id de un médico y devuelva por <b>OUTPUT</b> cuántas citas tiene. Luego ejecútalo para el médico 3 e imprime el resultado.',
    steps: [
      ['Crea el procedimiento uspContarCitas', 'CREATE PROCEDURE <nombre>', ['CREATE PROCEDURE uspContarCitas'], 0],
      ['Parámetros: @p_idMedico INT, y @p_total INT de salida', '@p_a TIPO, @p_b TIPO <palabra de salida>', ['@p_idMedico INT, @p_total INT OUTPUT'], 0],
      ['Palabra que separa la cabecera del cuerpo', 'A_', ['AS'], 0],
      ['Abre el cuerpo', 'BEGIN', ['BEGIN'], 0],
      ['Cuenta las citas de ese médico y guárdalo en @p_total', 'SELECT @p_total = COUNT(*) FROM <tabla> WHERE <col> = @p_…', ['SELECT @p_total = COUNT(*) FROM Citas WHERE IdMedico = @p_idMedico'], 1],
      ['Cierra el cuerpo', 'END', ['END'], 0],
      ['Separa el lote para poder ejecutarlo', 'G_', ['GO'], 0],
      ['Declara @total INT para recibir el resultado', 'DECLARE @<var> <TIPO>', ['DECLARE @total INT'], 0],
      ['Ejecuta el SP para el médico 3 recibiendo en @total', 'EXEC <sp> <valor>, @var <palabra de salida>', ['EXEC uspContarCitas 3, @total OUTPUT', 'EXEC uspContarCitas @p_idMedico = 3, @p_total = @total OUTPUT'], 0],
      ["Imprime 'Citas: ' + @total convertido a texto", "PRINT '<texto>' + CAST(@var AS VARCHAR)", ["PRINT 'Citas: ' + CAST(@total AS VARCHAR)", "PRINT 'Citas: ' + CONVERT(VARCHAR, @total)", "PRINT 'Citas: ' + CAST(@total AS VARCHAR(10))"], 0],
    ],
  },
  {
    id: 'b-insert', unit: 'sp', db: 'gimnasio', title: 'SP que valida e inserta',
    text: 'Crea <b>uspNuevoPlan</b> (nombre, precio). Si ya existe un plan con ese nombre imprime <b>El plan ya existe</b>; si no, calcula el nuevo id e insértalo.',
    steps: [
      ['Crea el procedimiento uspNuevoPlan', 'CREATE PROCEDURE <nombre>', ['CREATE PROCEDURE uspNuevoPlan'], 0],
      ['Parámetros: @p_nombre VARCHAR(30) y @p_precio DECIMAL(8,2)', '@p_a TIPO, @p_b TIPO', ['@p_nombre VARCHAR(30), @p_precio DECIMAL(8,2)'], 0],
      ['Separa cabecera y cuerpo', 'A_', ['AS'], 0],
      ['Abre el cuerpo', 'BEGIN', ['BEGIN'], 0],
      ['Si YA existe un plan con ese Nombre…', 'IF EXISTS(SELECT 1 FROM <tabla> WHERE <col> = @p_…)', ['IF EXISTS(SELECT 1 FROM Planes WHERE Nombre = @p_nombre)', 'IF EXISTS(SELECT * FROM Planes WHERE Nombre = @p_nombre)'], 1],
      ["…imprime 'El plan ya existe'", "PRINT '<texto>'", ["PRINT 'El plan ya existe'"], 2],
      ['Si no…', 'EL__', ['ELSE'], 1],
      ['Abre un bloque para varias instrucciones', 'BEGIN', ['BEGIN'], 1],
      ['Declara @v_id INT', 'DECLARE @<var> <TIPO>', ['DECLARE @v_id INT'], 2],
      ['Calcula el siguiente IdPlan y guárdalo en @v_id', 'SELECT @v = MAX(<id>) + 1 FROM <tabla>', ['SELECT @v_id = MAX(IdPlan) + 1 FROM Planes'], 2],
      ['Inserta el plan con @v_id, @p_nombre y @p_precio', 'INSERT INTO <tabla> VALUES (…)', ['INSERT INTO Planes VALUES (@v_id, @p_nombre, @p_precio)'], 2],
      ['Cierra el bloque del ELSE', 'END', ['END'], 1],
      ['Cierra el procedimiento', 'END', ['END'], 0],
    ],
  },
  {
    id: 'b-cursor', unit: 'cur', db: 'colegio', title: 'Cursor que recorre alumnos',
    text: 'Con un cursor, imprime el <b>nombre</b> y el <b>grado</b> de cada alumno, uno por uno.',
    steps: [
      ['Declara el cursor c_alumnos para…', 'DECLARE <cursor> CURSOR FOR', ['DECLARE c_alumnos CURSOR FOR'], 0],
      ['…seleccionar Nombre y Grado de Alumnos', 'SELECT <col>, <col> FROM <tabla>', ['SELECT Nombre, Grado FROM Alumnos'], 1],
      ['Declara @nombre VARCHAR(60) y @grado CHAR(2)', 'DECLARE @a TIPO, @b TIPO', ['DECLARE @nombre VARCHAR(60), @grado CHAR(2)'], 0],
      ['Abre el cursor', 'OPEN <cursor>', ['OPEN c_alumnos'], 0],
      ['Lee la primera fila en @nombre y @grado', 'FETCH <cursor> INTO @a, @b', ['FETCH c_alumnos INTO @nombre, @grado', 'FETCH NEXT FROM c_alumnos INTO @nombre, @grado'], 0],
      ['Mientras la lectura haya salido bien…', 'WHILE <variable global> = 0', ['WHILE @@FETCH_STATUS = 0'], 0],
      ['Abre el bloque del bucle', 'BEGIN', ['BEGIN'], 0],
      ["Imprime @nombre + ' - ' + @grado", 'PRINT …', ["PRINT @nombre + ' - ' + @grado"], 1],
      ['Lee la siguiente fila (¡no lo olvides!)', 'FETCH <cursor> INTO @a, @b', ['FETCH c_alumnos INTO @nombre, @grado', 'FETCH NEXT FROM c_alumnos INTO @nombre, @grado'], 1],
      ['Cierra el bucle', 'END', ['END'], 0],
      ['Cierra el cursor', 'CLOSE <cursor>', ['CLOSE c_alumnos'], 0],
      ['Libera el cursor', 'DEALLOCATE <cursor>', ['DEALLOCATE c_alumnos'], 0],
    ],
  },
  {
    id: 'b-funcion', unit: 'fn', db: 'cine', title: 'Función y uso en SELECT',
    text: 'Crea <b>dbo.fu_total</b> que reciba un precio y una cantidad, y devuelva precio × cantidad. Luego muestra cada función con el total de 4 boletos.',
    steps: [
      ['Crea la función dbo.fu_total con @p_precio DECIMAL(6,2) y @p_cant INT', 'CREATE FUNCTION dbo.<nombre>(@a TIPO, @b TIPO)', ['CREATE FUNCTION dbo.fu_total(@p_precio DECIMAL(6,2), @p_cant INT)'], 0],
      ['Indica que devuelve un DECIMAL(8,2)', 'RETURN_ <TIPO>', ['RETURNS DECIMAL(8,2)'], 0],
      ['Separa cabecera y cuerpo', 'A_', ['AS'], 0],
      ['Abre el cuerpo', 'BEGIN', ['BEGIN'], 0],
      ['Devuelve el precio por la cantidad', 'RETURN_ <cálculo>', ['RETURN @p_precio * @p_cant'], 1],
      ['Cierra el cuerpo', 'END', ['END'], 0],
      ['Separa el lote', 'G_', ['GO'], 0],
      ['Muestra IdFuncion y el total de 4 boletos de cada función', 'SELECT <col>, dbo.<fn>(<col>, 4) FROM <tabla>', ['SELECT IdFuncion, dbo.fu_total(Precio, 4) FROM Funciones', 'SELECT IdFuncion, dbo.fu_total(Precio, 4) AS Total FROM Funciones'], 0],
    ],
  },
  {
    id: 'b-tx', unit: 'tx', db: 'banco', title: 'Transferencia con transacción',
    text: "Pasa <b>100</b> de la cuenta <b>'A1'</b> a la <b>'B2'</b>. Si algo falla, deshaz todo.",
    steps: [
      ['Empieza la transacción', 'BEGIN TRAN______', ['BEGIN TRANSACTION', 'BEGIN TRAN'], 0],
      ['Abre el bloque que intenta', 'BEGIN ___', ['BEGIN TRY'], 0],
      ["Resta 100 al Saldo de la cuenta 'A1'", 'UPDATE <tabla> SET <col> = <col> - 100 WHERE <col> = …', ["UPDATE Cuentas SET Saldo = Saldo - 100 WHERE NumCuenta = 'A1'"], 1],
      ["Suma 100 al Saldo de la cuenta 'B2'", 'UPDATE <tabla> SET <col> = <col> + 100 WHERE <col> = …', ["UPDATE Cuentas SET Saldo = Saldo + 100 WHERE NumCuenta = 'B2'"], 1],
      ['Todo salió bien: confirma', 'COMMIT …', ['COMMIT TRANSACTION', 'COMMIT TRAN', 'COMMIT'], 1],
      ['Cierra el TRY', 'END ___', ['END TRY'], 0],
      ['Abre el CATCH', 'BEGIN _____', ['BEGIN CATCH'], 0],
      ['Algo falló: deshaz todo', 'ROLLBACK …', ['ROLLBACK TRANSACTION', 'ROLLBACK TRAN', 'ROLLBACK'], 1],
      ["Imprime 'Error: ' + el texto del error", "PRINT '<texto>' + <función>()", ["PRINT 'Error: ' + ERROR_MESSAGE()"], 1],
      ['Cierra el CATCH', 'END _____', ['END CATCH'], 0],
    ],
  },
  {
    id: 'b-trigger', unit: 'trg', db: 'colegio', title: 'Trigger que impide notas > 20',
    text: 'Crea un trigger en <b>Notas</b> que, al insertar o actualizar, impida guardar notas mayores a 20.',
    steps: [
      ['Crea el trigger trg_nota…', 'CREATE TRIGGER <nombre>', ['CREATE TRIGGER trg_nota'], 0],
      ['…sobre la tabla Notas', '__ <tabla>', ['ON Notas'], 0],
      ['Que se dispare al insertar o actualizar', 'FOR <evento>, <evento>', ['FOR INSERT, UPDATE', 'AFTER INSERT, UPDATE', 'FOR UPDATE, INSERT', 'AFTER UPDATE, INSERT'], 0],
      ['Separa cabecera y cuerpo', 'A_', ['AS'], 0],
      ['Abre el cuerpo', 'BEGIN', ['BEGIN'], 0],
      ['Si en lo NUEVO hay alguna Nota mayor a 20…', 'IF EXISTS(SELECT 1 FROM <tabla virtual> WHERE …)', ['IF EXISTS(SELECT 1 FROM inserted WHERE Nota > 20)', 'IF EXISTS(SELECT * FROM inserted WHERE Nota > 20)'], 1],
      ['Abre el bloque', 'BEGIN', ['BEGIN'], 1],
      ['Revierte la operación', 'ROLLBACK …', ['ROLLBACK TRANSACTION', 'ROLLBACK TRAN', 'ROLLBACK'], 2],
      ["Avisa 'NOTA INVALIDA' con severidad 10", "RAISERROR('<mensaje>', 10, 1)", ["RAISERROR('NOTA INVALIDA', 10, 1)"], 2],
      ['Cierra el bloque', 'END', ['END'], 1],
      ['Cierra el trigger', 'END', ['END'], 0],
    ],
  },
  {
    id: 'b-audit', unit: 'trg', db: 'gimnasio', title: 'Trigger de auditoría',
    text: 'Cada vez que se <b>elimine</b> una membresía, guarda en <b>Auditoria</b> la acción, el usuario y la fecha.',
    steps: [
      ['Crea el trigger trg_audit', 'CREATE TRIGGER <nombre>', ['CREATE TRIGGER trg_audit'], 0],
      ['…sobre la tabla Membresias', '__ <tabla>', ['ON Membresias'], 0],
      ['Solo cuando se elimine', 'FOR <evento>', ['FOR DELETE', 'AFTER DELETE'], 0],
      ['Separa cabecera y cuerpo', 'A_', ['AS'], 0],
      ['Abre el cuerpo', 'BEGIN', ['BEGIN'], 0],
      ["Inserta en Auditoria: 'ELIMINO MEMBRESIA', el login y la fecha actual", "INSERT INTO <tabla> VALUES ('<texto>', <fn login>(), <fn fecha>())", ["INSERT INTO Auditoria VALUES ('ELIMINO MEMBRESIA', SUSER_SNAME(), GETDATE())"], 1],
      ['Cierra el trigger', 'END', ['END'], 0],
    ],
  },
];
